07:01:07.684 Running build in Washington, D.C., USA (East) – iad1
07:01:07.684 Build machine configuration: 2 cores, 8 GB
07:01:07.900 Cloning github.com/Rami1125/ai-saban94-chat (Branch: main, Commit: 8a72017)
07:01:08.331 Cloning completed: 431.000ms
07:01:09.696 Restored build cache from previous deployment (HTv64PnSHenhxXDABL1eWjYw9KbT)
07:01:10.940 Running "vercel build"
07:01:11.583 Vercel CLI 50.28.0
07:01:11.940 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
07:01:11.940 Using pnpm@10.x based on project creation date
07:01:11.940 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
07:01:11.956 Running "install" command: `pnpm install --no-frozen-lockfile`...
07:01:12.856 Progress: resolved 1, reused 0, downloaded 0, added 0
07:01:13.859 Progress: resolved 52, reused 0, downloaded 44, added 0
07:01:14.860 Progress: resolved 57, reused 0, downloaded 49, added 0
07:01:15.860 Progress: resolved 66, reused 0, downloaded 58, added 0
07:01:16.860 Progress: resolved 68, reused 0, downloaded 60, added 0
07:01:17.861 Progress: resolved 139, reused 0, downloaded 109, added 0
07:01:18.863 Progress: resolved 192, reused 0, downloaded 186, added 0
07:01:19.946 Progress: resolved 207, reused 0, downloaded 200, added 0
07:01:20.993 Progress: resolved 226, reused 0, downloaded 213, added 0
07:01:22.000 Progress: resolved 246, reused 0, downloaded 217, added 0
07:01:23.011 Progress: resolved 312, reused 0, downloaded 269, added 0
07:01:24.012 Progress: resolved 316, reused 0, downloaded 269, added 0
07:01:25.016 Progress: resolved 342, reused 0, downloaded 299, added 0
07:01:26.023 Progress: resolved 377, reused 0, downloaded 345, added 0
07:01:27.030 Progress: resolved 445, reused 0, downloaded 365, added 0
07:01:28.030 Progress: resolved 448, reused 0, downloaded 392, added 0
07:01:28.373 Already up to date
07:01:28.418 Progress: resolved 452, reused 0, downloaded 407, added 0, done
07:01:28.620 
07:01:28.626 Done in 16.5s using pnpm v10.28.0
07:01:28.683 Detected Next.js version: 16.0.10
07:01:28.733 Running "pnpm run build"
07:01:29.023 
07:01:29.023 > ai-saban94-chat@0.1.0 build /vercel/path0
07:01:29.023 > next build
07:01:29.023 
07:01:29.352 [baseline-browser-mapping] The data in this module is over two months old.  To ensure accurate Baseline data, please update: `npm i baseline-browser-mapping@latest -D`
07:01:29.843    ▲ Next.js 16.0.10 (Turbopack)
07:01:29.844 
07:01:29.883    Creating an optimized production build ...
07:01:30.026 [baseline-browser-mapping] The data in this module is over two months old.  To ensure accurate Baseline data, please update: `npm i baseline-browser-mapping@latest -D`
07:01:46.811 
07:01:46.811 > Build error occurred
07:01:46.815 Error: Turbopack build failed with 1 errors:
07:01:46.816 ./app/checkout/page.tsx:38:38
07:01:46.816 Parsing ecmascript source code failed
07:01:46.816 [0m [90m 36 |[39m   [36mconst[39m addToCart [33m=[39m (product[33m:[39m any[33m,[39m color [33m=[39m [32m"סטנדרט"[39m) [33m=>[39m {
07:01:46.816  [90m 37 |[39m     setCart(prev [33m=>[39m [[33m...[39mprev[33m,[39m { [33m...[39mproduct[33m,[39m selectedColor[33m:[39m color[33m,[39m quantity[33m:[39m [35m1[39m }])[33m;[39m
07:01:46.816 [31m[1m>[22m[39m[90m 38 |[39m     toast[33m.[39msuccess([32m`${product.name} {`[39mנוסף לסל[32m`}`[39m)[33m;[39m
07:01:46.817  [90m    |[39m                                      [31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m
07:01:46.817  [90m 39 |[39m   }[33m;[39m
07:01:46.817  [90m 40 |[39m
07:01:46.817  [90m 41 |[39m   [36mconst[39m handleScanProduct [33m=[39m [36masync[39m (sku[33m:[39m string) [33m=>[39m {[0m
07:01:46.817 
07:01:46.818 Expected ',', got 'נוסף'
07:01:46.818 
07:01:46.818 
07:01:46.818     at <unknown> (./app/checkout/page.tsx:38:38)
07:01:46.876  ELIFECYCLE  Command failed with exit code 1.
07:01:46.897 Error: Command "pnpm run build" exited with 1
